create_main_pyfile <- function(filename, iscen, igrp){
  
  MDAFilePath = sprintf('MDAfiles/STH_MDA_scen%g.csv', iscen)
  PickleFile = sprintf('output/OutputPickle_scen%g_grp%g.p', iscen, igrp)
  
  cat(file=filename, paste("import functools"))
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("import time"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("import numpy as np"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("import pandas as pd"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("import platform"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("import sys"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\n", append = T)
  
  # multiprocessing
  # cat(file=filename, paste("if __name__ == \'__main__\':"), append = T)
  # cat(file=filename, "\n", append = T)
  # cat(file=filename, "\t", paste("if platform.system() == \"Darwin\":"), append = T)
  # cat(file=filename, "\n", append = T)
  # cat(file=filename, "\t", "\t", paste("multiprocessing.set_start_method(\'spawn\' ,force=True)"), append = T)
  # cat(file=filename, "\n", append = T)
  # cat(file=filename, "\n", append = T)
  
  # STH simulation
  cat(file=filename, paste("from sth_simulation.helsim_RUN import STH_Simulation"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\n", append = T)
  
  # timer function
  cat(file=filename, paste("def timer(func):"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", paste("@functools.wraps(func)"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", paste("def wrapper_timer(*args, **kwargs):"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("print(f\"-> Running {func.__name__!r}\")"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("start_time = time.perf_counter()    # 1"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("value = func(*args, **kwargs)"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("end_time = time.perf_counter()      # 2"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("run_time = end_time - start_time    # 3"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("print(f\"=> Finished {func.__name__!r} in {run_time:.4f} secs\\n\\n\")"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", paste("return value"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", paste("return wrapper_timer"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\n", append = T)
  
  # first simulation function
  cat(file=filename, paste("@timer"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("def test():"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", paste("STH_Simulation(paramFileName='AscarisParameters_moderate.txt',"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t","\t", "\t", "\t", paste("demogName='WHOGeneric',"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("MDAFilePath=\'", MDAFilePath, "\',", sep=""), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("prevKKSACFilePath=\'", prevalence_output, "\',", sep=""), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("prevMHISACFilePath=\'", prevalence_output2, "\',", sep=""), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("RkFilePath=\'", inputRk, "\',", sep=""), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("nYears=18,"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("outputFrequency=1,"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("numReps=None,"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("SaveOutput=False,"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("OutSimFilePath=None,"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("InSimFilePath=None)"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\n", append = T)
  
  # second simulation function
  cat(file=filename, paste("@timer"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, paste("def rerun():"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", paste("STH_Simulation(paramFileName='AscarisParameters_moderate.txt',"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t","\t", "\t", "\t", paste("demogName='WHOGeneric',"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("MDAFilePath=\'", MDAFilePath, "\',", sep=""), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("prevKKSACFilePath=\'", prevalence_output, "\',", sep=""), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("prevMHISACFilePath=\'", prevalence_output2, "\',", sep=""), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("RkFilePath=\'", inputRk, "\',", sep=""), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("nYears=18,"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("outputFrequency=1,"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("numReps=None,"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("SaveOutput=True,"), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("OutSimFilePath=\'", PickleFile, "\',", sep=""), append = T)
  cat(file=filename, "\n", append = T)
  cat(file=filename, "\t", "\t", "\t", "\t", paste("InSimFilePath=None)"), append = T)
}

